// burger-constructor
export const ADD_INGREDIENT_TO_CONSTRUCTOR: 'ADD_INGREDIENT_TO_CONSTRUCTOR' = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR: 'REMOVE_INGREDIENT_TO_CONSTRUCTOR' = 'REMOVE_INGREDIENT_TO_CONSTRUCTOR';
export const REPLACE_BUN_IN_CONSTRUCTOR: 'REPLACE_BUN_IN_CONSTRUCTOR' = 'REPLACE_BUN_IN_CONSTRUCTOR';
export const UPDATE_CONSTRUCTOR_FROM_DRAGGING_CONTAINER: 'UPDATE_CONSTRUCTOR_FROM_DRAGGING_CONTAINER' = 'UPDATE_CONSTRUCTOR_FROM_DRAGGING_CONTAINER';
export const COPY_CONSTRUCTOR_TO_DRAGGING_CONTAINER: 'COPY_CONSTRUCTOR_TO_DRAGGING_CONTAINER' = 'COPY_CONSTRUCTOR_TO_DRAGGING_CONTAINER';
export const REPLACE_ITEMS_IN_DRAGGING_CONTAINER: 'REPLACE_ITEMS_IN_DRAGGING_CONTAINER' = 'REPLACE_ITEMS_IN_DRAGGING_CONTAINER';
export const RESET_DRAGGING_CONTAINER: 'RESET_DRAGGING_CONTAINER' = 'RESET_DRAGGING_CONTAINER';
export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';

// burger-ingredients
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const INCREASE_INGREDIENT: 'INCREASE_INGREDIENT' = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT: 'DECREASE_INGREDIENT' = 'DECREASE_INGREDIENT';
export const RESET_INGREDIENTS_COUNT: 'RESET_INGREDIENTS_COUNT' = 'RESET_INGREDIENTS_COUNT';

// popups
export const GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST' = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED';
export const CLOSE_ORDER_DETAILS: 'CLOSE_ORDER_DETAILS' = 'CLOSE_ORDER_DETAILS';
export const OPEN_ERROR_POPUP: 'OPEN_ERROR_POPUP' = 'OPEN_ERROR_POPUP';
export const CLOSE_ERROR_POPUP: 'CLOSE_ERROR_POPUP' = 'CLOSE_ERROR_POPUP';
export const OPEN_SUCCESS_POPUP: 'OPEN_SUCCESS_POPUP' = 'OPEN_SUCCESS_POPUP';
export const CLOSE_SUCCESS_POPUP: 'CLOSE_SUCCESS_POPUP' = 'CLOSE_SUCCESS_POPUP';

// profile
export const UPDATE_TOKEN: 'UPDATE_TOKEN' = 'UPDATE_TOKEN';
export const SET_USER: 'SET_USER' = 'SET_USER';
export const CLEAR_USER: 'CLEAR_USER' = 'CLEAR_USER';
export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const EDIT_USER_REQUEST: 'EDIT_USER_REQUEST' = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS' = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED: 'EDIT_USER_FAILED' = 'EDIT_USER_FAILED';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

// login
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

// register
export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

// forgot-password
export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';

// reset-password
export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

// ws-actions
export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_STOP: 'WS_FEED_CONNECTION_STOP' = 'WS_FEED_CONNECTION_STOP';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' = 'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' = 'WS_FEED_CONNECTION_CLOSED';
export const WS_GET_FEED: 'WS_GET_FEED_DATA' = 'WS_GET_FEED_DATA';
export const WS_USER_ORDERS_CONNECTION_START: 'WS_USER_ORDERS_CONNECTION_START' = 'WS_USER_ORDERS_CONNECTION_START';
export const WS_USER_ORDERS_CONNECTION_STOP: 'WS_USER_ORDERS_CONNECTION_STOP' = 'WS_USER_ORDERS_CONNECTION_STOP';
export const WS_USER_ORDERS_CONNECTION_SUCCESS: 'WS_USER_ORDERS_CONNECTION_SUCCESS' = 'WS_USER_ORDERS_CONNECTION_SUCCESS';
export const WS_USER_ORDERS_CONNECTION_ERROR: 'WS_USER_ORDERS_CONNECTION_ERROR' = 'WS_USER_ORDERS_CONNECTION_ERROR';
export const WS_USER_ORDERS_CONNECTION_CLOSED: 'WS_USER_ORDERS_CONNECTION_CLOSED' = 'WS_USER_ORDERS_CONNECTION_CLOSED';
export const WS_GET_USER_ORDERS: 'WS_GET_USER_FEED' = 'WS_GET_USER_FEED';
export const FEED_REQUEST: 'FEED_REQUEST' = 'FEED_REQUEST';
export const FEED_SUCCESS: 'FEED_SUCCESS' = 'FEED_SUCCESS';
export const FEED_FAILED: 'FEED_FAILED' = 'FEED_FAILED';
