export const UPDATE_CONSTRUCTOR_FROM_DRAGGING_CONTAINER = 'UPDATE_CONSTRUCTOR_FROM_DRAGGING_CONTAINER';
export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_TO_CONSTRUCTOR';
export const REPLACE_BUN_IN_CONSTRUCTOR = 'REPLACE_BUN_IN_CONSTRUCTOR';
export const COPY_CONSTRUCTOR_TO_DRAGGING_CONTAINER = 'COPY_CONSTRUCTOR_TO_DRAGGING_CONTAINER';
export const REPLACE_ITEMS_IN_DRAGGING_CONTAINER = 'REPLACE_ITEMS_IN_DRAGGING_CONTAINER';
export const RESET_DRAGGING_CONTAINER = 'RESET_DRAGGING_CONTAINER';
