export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_TO_CONSTRUCTOR';
export const REPLACE_BUN_IN_CONSTRUCTOR = 'REPLACE_BUN_IN_CONSTRUCTOR';
